### ISSUE TITLE
diagrama de clase

### ISSUE THREAD

**Issue by 27Fer12** [SistemasTecTlaxiaco/actividad-3-practica-architect-27Fer12#1]
[diagramas de clase.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-27Fer12/files/12554434/diagramas.de.clase.pdf)

**Comment by Alvaro2-0** [comment]
17/20
Checar las faltas de ortografía.
Checar el espaciado.
Checar el índice.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
